### PR TITLE
Add kubernetes as an option to bug report

### PR DESCRIPTION
**Pull request by mzac**
Add kubernetes as an environment option

### CODE REVIEW

**Comment by jesserockz** [comment]
While I understand how this might help you, to me `kubernetes` is just `docker` and I highly doubt you will be able to get `kubernetes` specific help with any issues...

**Comment by mzac** [comment]
Well, kinda but not really.  Kubernetes is moving away from Docker (https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/) and it uses containerd instead.  I've had some challenges getting Esphome working on Kubernetes so I think it could be a valid request.  For example, creating the deployment is not the same as docker/compose and networking is a bit different (host mode).  I've also run into an issue with discovery if I'm running Esphome on a x86 vs arm64 system.  They don't act the same for some reason.  

My two cents...

**Comment by jesserockz** [comment]
I just feel like adding it to the list kind of makes it seem like a "supported" method of install, and I do not want to go down that path personally.

**Comment by mzac** [comment]
Ok, I see what you mean about a supported method.  Makes sense ;)  I know that Kubernetes isn't for everyone is is very complex compared to Docker.

**Pull request closed without merging**
